name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
# on:
#   workflow_dispatch:

permissions:
  contents: read
  id-token: write 
env:
  SERVICE_NAME: "cloud-run-service"
  PROJECT_ID: "cloud-app-net"
  REGION: "us-central1"
  IMAGE: cloud-app  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
    - name: Checkout Code
      uses: actions/checkout@v4

      # Authenticate to GCP using Workload Identity Federation
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/149074426396/locations/global/workloadIdentityPools/githubpool/providers/githubprovider"
        service_account: "github-actions-sa@cloud-app-net.iam.gserviceaccount.com"

      # Set up the Google Cloud SDK CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    # Submit build to Cloud Build (compiles & pushes image to Artifact Registry)
    - name: Submit Cloud Build
      run: |
        IMAGE_TAG="$gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}"
        gcloud builds submit --tag "${IMAGE_TAG}" .
        echo "IMAGE_NAME=$IMAGE_TAG" >> $GITHUB_ENV


    # Deploy the freshly built image to Cloud Run
    - name: Deploy to Cloud Run
      id: deploy-run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: ${{ env.IMAGE_NAME }}
        # Optional parameters:
        flags: '--allow-unauthenticated --memory=512Mi'

    # Output the live Cloud Run deployment URL
    - name: Show Cloud Run URL
      run: | 
        echo "Your application is live at ${{ steps.deploy-run.outputs.url }}"
